apiVersion: apps/v1
kind: Deployment
# namespace: dev
metadata:
  name: nginx-deployment
  labels:
    environment: Deployment
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
           - containerPort: 7749
             protocol: TCP
        resources:
          requests:
            memory: 10Mi
            cpu: 100m
          limits:
           memory: 512Mi
           cpu: "1"
        # requests:
        #    memory: 256Mi
        #    cpu: "0.2"
        