apiVersion: v1
kind: Service
# namespace: dev
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  ports:
  - port: 8864
    protocol: TCP
    targetPort: 7749
  selector:
    app: nginx
  type: ClusterIP
